apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-earth-qgs
  annotations:
    # Add supports for Halo App Store
    # https://www.halo.run/store/apps/app-KgWqR
    "store.halo.run/app-id": "app-KgWqR"
    # 链接管理：https://www.halo.run/store/apps/app-hfbQg
    # 图库管理：https://www.halo.run/store/apps/app-BmQJW
    # 瞬间：https://www.halo.run/store/apps/app-SnwWD
    # Shiki 代码高亮：https://www.halo.run/store/apps/app-kzloktzn
    # lightgallery.js 灯箱：https://www.halo.run/store/apps/app-OoggD
    "store.halo.run/recommended-apps": '["app-hfbQg", "app-BmQJW", "app-SnwWD", "app-kzloktzn", "app-OoggD"]'
spec:
  displayName: Earth-qgs
  author:
    name: qianshun
    website: https://www.qgs.life
  description: updated by qianshun  theme-earth for Halo 2.0
  logo: https://oss.qgs.life/haloblog/%7Byear%7D/%7Bmonth%7D/logo_400.jpg
  homepage: https://www.qgs.life
  repo: https://github.com/qianshun/theme-earth
  issues: https://github.com/qianshun/theme-earth/issues
  settingName: "theme-earth-setting"
  configMapName: "theme-earth-configMap"
  version: 1.17.1
  requires: ">=2.22.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/qianshun/theme-earth/blob/main/LICENSE"
